using Test, ThreadPools
include("teststatic.jl")
include("testlogstatic.jl")
include("testq.jl")
include("testlogq.jl")
include("testmacros.jl")
include("testmaps.jl")
include("testforeach.jl")
include("testlogfcns.jl")
include("stacktests.jl")
include("testspawnat.jl")
include("testmultidim.jl")
include("testmultiarg.jl")
include("testmisc.jl")
include("testplots.jl")
include("errorhandling.jl")
include("spawn_background.jl")
